version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=celulou
      - POSTGRES_PASSWORD=celulou123
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U celulou"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    networks:
      - net

  db-test:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    volumes:
      - postgres:/var/lib/test-data/data
    expose:
      - '5431'
    ports:
      - '5431:5432'
    networks:
      - net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net

volumes:
  postgres:

networks:
  net: