version: '3.8'
services:
  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U celulou"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    networks:
      - net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - net


volumes:
  postgres:

networks:
  net: